- build.gradle.kts
- src/main/kotlin/fi/metatavu/oss/api/impl/AbstractApi.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/abstracts/AbstractRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/surveys/SurveyController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/surveys/SurveyEntity.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/surveys/SurveyRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/surveys/SurveyTranslator.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/surveys/SurveysApiImpl.kt
- src/main/kotlin/fi/metatavu/oss/api/metadata/DBMetadata.kt
- src/main/kotlin/fi/metatavu/oss/api/metadata/MetadataTranslator.kt
- src/main/resources/db/changeLog.xml
- src/native-test/kotlin/fi/metatavu/oss/api/test/functional/tests/NativeSurveyTestIT.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/auth/TestBuilderAuthentication.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/impl/ApiTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/impl/SurveysTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/SurveyTestIT.kt
https://github.com/Metatavu/oss-surveys-api/issues/5
Includes the other PR with the bootstap, should be merged after it
> Feature 5 surveys

- src/main/kotlin/fi/metatavu/oss/api/impl/abstracts/AbstractRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devices/DeviceController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devices/DeviceRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/requests/DeviceRequestController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/requests/DeviceRequestRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/surveys/SurveyController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/surveys/SurveyEntity.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/surveys/SurveyRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/surveys/SurveyTranslator.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/surveys/SurveysApiImpl.kt
- src/main/resources/db/changeLog.xml
- src/test/kotlin/fi/metatavu/oss/api/test/functional/impl/SurveysTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/SurveyTestIT.kt
> Feature 13 survey status

- src/main/kotlin/fi/metatavu/oss/api/impl/surveys/SurveyController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/surveys/SurveyEntity.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/surveys/SurveyRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/surveys/SurveyTranslator.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/surveys/SurveysApiImpl.kt
- src/main/resources/db/changeLog.xml
- src/test/kotlin/fi/metatavu/oss/api/test/functional/impl/SurveysTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/DeviceSurveysTestIT.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/SurveyTestIT.kt
> Added description and timeout for Surveys

- src/main/kotlin/fi/metatavu/oss/api/impl/devices/DeviceController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devices/DeviceRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devices/DevicesApiImpl.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/impl/DevicesTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/DeviceTestIT.kt
https://github.com/Metatavu/oss-surveys-api/issues/28
> Feature 28 device status filter

- src/main/kotlin/fi/metatavu/oss/api/impl/realtime/mqtt/ReactiveStatusConsumer.kt
> Fixed status consumer

- src/main/kotlin/fi/metatavu/oss/api/impl/AbstractApi.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devices/DeviceController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/DeviceSurveysApiImpl.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/devicesurveydata/DeviceSurveyDataApiImpl.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/devicesurveydata/DeviceSurveyDataTranslator.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/translate/AbstractTranslator.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/auth/TestBuilderAuthentication.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/impl/DeviceSurveyDatasTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/impl/DeviceSurveysTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/impl/DevicesTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/AbstractResourceTest.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/DeviceSurveyDataTestIT.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/DeviceSurveysTestIT.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/DeviceTestIT.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/SchedulerTestIT.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/SurveyTestIT.kt
https://github.com/Metatavu/oss-surveys-api/issues/30
> Feature 30 device survey data

- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/devicesurveydata/DeviceSurveyDataTranslator.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/layouts/LayoutController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/layouts/LayoutTranslator.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/layouts/LayoutVariableEntity.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/layouts/LayoutVariableRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/PagePropertyEntity.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/PagePropertyRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/PagesApiImpl.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/PagesController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/PagesTranslator.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/questions/PageQuestionController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/questions/PageQuestionEntity.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/questions/PageQuestionRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/questions/PageQuestionTranslator.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/questions/QuestionOptionEntity.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/questions/QuestionOptionRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/translate/AbstractTranslator.kt
- src/main/resources/db/changeLog.xml
- src/test/kotlin/fi/metatavu/oss/api/test/functional/impl/LayoutTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/DeviceSurveyDataTestIT.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/LayoutTestIT.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/PageTestIT.kt
https://github.com/Metatavu/oss-surveys-api/issues/34
> Feature 34 page options properties

- src/main/kotlin/fi/metatavu/oss/api/impl/pages/PageEntity.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/PageRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/PagesController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/PagesTranslator.kt
- src/main/resources/db/changeLog.xml
- src/test/kotlin/fi/metatavu/oss/api/test/functional/impl/PagesTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/DeviceSurveyDataTestIT.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/PageTestIT.kt
> Added nextButtonVisible to Page

- src/main/kotlin/fi/metatavu/oss/api/impl/requests/DeviceRequestController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/requests/DeviceRequestRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/requests/DeviceRequestsApiImpl.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/impl/DeviceRequestsTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/DeviceRequestsTestIT.kt
> Added listDeviceRequests endpoint

- src/main/kotlin/fi/metatavu/oss/api/impl/devices/DeviceController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/DeviceSurveysApiImpl.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/requests/DeviceRequestController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/requests/DeviceRequestEntity.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/requests/DeviceRequestTranslator.kt
- src/main/resources/db/changeLog.xml
- src/test/kotlin/fi/metatavu/oss/api/test/functional/impl/DeviceSurveysTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/DeviceRequestsTestIT.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/DeviceSurveysTestIT.kt
> Feature 44 device request new fields

- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/DeviceSurveyController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/DeviceSurveysApiImpl.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/PageAnswerController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/repositories/PageAnswerRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/surveys/SurveyController.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/impl/DeviceSurveysTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/AbstractResourceTest.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/DeviceSurveyDataTestIT.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/DeviceSurveysTestIT.kt
> Feature 48 survey statistics

- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/DeviceSurveyController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/DeviceSurveysApiImpl.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/PageAnswerController.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/impl/DeviceSurveysTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/DeviceSurveysTestIT.kt
> Fixes issue with unpublished survey statistics

- src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/repositories/PageAnswerSingleRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/questions/PageQuestionController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/questions/PageQuestionRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/questions/QuestionOptionRepository.kt
> Fixes issue #51

- src/main/kotlin/fi/metatavu/oss/api/impl/devices/DeviceController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devices/DeviceEntity.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devices/DeviceRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devices/DeviceTranslator.kt
- src/main/resources/db/changeLog.xml
> Attempt to fix issue 57

- src/main/resources/db/changeLog.xml
- src/main/resources/db/html-templates.sql
- src/main/resources/resources-config.json
> Added migration described in issue #62

- build.gradle.kts
- settings.gradle.kts
- src/main/kotlin/fi/metatavu/oss/api/impl/devices/DeviceController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/DeviceSurveyController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/DeviceSurveyRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/DeviceSurveysApiImpl.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/devicesurveydata/DeviceSurveyDataApiImpl.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/PagesApiImpl.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/scheduler/ScheduledSurveyPublisher.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/surveys/SurveysApiImpl.kt
- src/main/resources/application.properties
- src/test/kotlin/fi/metatavu/oss/api/test/functional/impl/DeviceSurveysTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/impl/SurveysTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/resources/LocalTestProfile.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/SchedulerTestIT.kt
> Refined scheduled survey publication

- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/DeviceSurveyController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/DeviceSurveyEntity.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/DeviceSurveyRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/DeviceSurveysApiImpl.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/scheduler/ScheduledSurveyPublisher.kt
- src/main/resources/db/changeLog.xml
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/AbstractResourceTest.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/DeviceSurveysTestIT.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/LayoutTestIT.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/SurveyTestIT.kt
> Refine scheduled survey publication

- src/main/kotlin/fi/metatavu/oss/api/impl/devices/DeviceController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devices/DeviceEntity.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/devicesurveydata/DeviceSurveyDataTranslator.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/questions/PageQuestionTranslator.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/translate/AbstractTranslator.kt
- src/main/resources/db/changeLog.xml
> Bugfix 70 fix for plain text devices

- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/devicesurveydata/DeviceSurveyDataTranslator.kt
> fixed issue with double h1 tags in preview

- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/devicesurveydata/DeviceSurveyDataApiImpl.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/PageAnswerController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/entities/PageAnswerBaseEntity.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/repositories/PageAnswerMultiRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/repositories/PageAnswerRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/repositories/PageAnswerSingleRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/repositories/PageAnswerTextRepository.kt
- src/main/resources/db/changeLog.xml
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/AbstractResourceTest.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/DeviceSurveyDataTestIT.kt
> Feature 81 duplicate answer detection

- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/devicesurveydata/DeviceSurveyDataApiImpl.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/PageAnswerController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/PageAnswerTranslator.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/entities/PageAnswerBaseEntity.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/repositories/PageAnswerMultiRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/repositories/PageAnswerSingleRepository.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/repositories/PageAnswerTextRepository.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/impl/DeviceSurveyDatasTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/impl/PagesTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/AbstractResourceTest.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/DeviceSurveyDataTestIT.kt
> Added support for answer submission timestamps from device

- src/main/kotlin/fi/metatavu/oss/api/impl/devices/DeviceController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/devicesurveys/devicesurveydata/DeviceSurveyDataApiImpl.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/PageAnswerController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/questions/PageQuestionController.kt
- src/main/kotlin/fi/metatavu/oss/api/impl/pages/questions/QuestionOptionRepository.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/AbstractResourceTest.kt
- src/test/kotlin/fi/metatavu/oss/api/test/functional/tests/DeviceSurveyDataTestIT.kt
> Feature 87 set answers without answer id to dummy answer

- .gitignore
- src/main/kotlin/fi/metatavu/oss/api/configuration/MqttChannelConfigurator.kt
- src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource
- src/main/resources/application.properties
- src/test/kotlin/fi/metatavu/oss/api/test/functional/resources/MqttResource.kt
> Fixed issue with tests
